#!/usr/bin/env python3
"""Zoe Evolution Engine: auto-generates and maintains the project's persistent memory + indexes.

The point: future Claude Code sessions (and Zoe) never lose project knowledge. This scans the REAL
repo and (re)writes a set of always-current index files into project-memory/, then mirrors the key
ones into the Obsidian vault so they are searchable. No manual registration -- run it and every
skill, plugin, command, tool, and automation is documented from reality.

  python tools/zoe_evolution.py                       regenerate all index/memory files
  python tools/zoe_evolution.py --session "summary"   also append a SESSION_HISTORY entry

Generates project-memory/: MASTER_MEMORY, PROJECT_STATE, ARCHITECTURE, FEATURE_INDEX, PLUGIN_INDEX,
SKILL_INDEX, COMMAND_REFERENCE, CONNECTOR_INDEX, AUTOMATION_INDEX, CHANGELOG, ROADMAP, CURRENT_TASK,
KNOWN_ISSUES, SESSION_HISTORY. Best-effort; never raises.
"""
import os, sys, glob, re, subprocess, time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PM = os.path.join(ROOT, "project-memory")
NOW = time.strftime("%Y-%m-%d %H:%M:%S")

def sh(cmd):
    try:
        return subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, timeout=20).stdout.strip()
    except Exception:
        return ""

def read(p):
    try:
        with open(p, encoding="utf-8") as f: return f.read()
    except Exception:
        return ""

def write(name, body):
    try:
        os.makedirs(PM, exist_ok=True)
        body = body.replace(chr(0x2014), "-").replace(chr(0x2013), "-")   # keep generated docs dash-clean
        with open(os.path.join(PM, name), "w", encoding="utf-8") as f:
            f.write("<!-- auto-generated by tools/zoe_evolution.py on " + NOW + ". Re-run to refresh. -->\n\n" + body)
        return True
    except Exception:
        return False

def first_doc(path):
    """First meaningful docstring/comment line of a file, for one-line descriptions."""
    txt = read(path)
    m = re.search(r'"""(.+?)(?:\n|""")', txt, re.S)
    if m: return m.group(1).strip().split("\n")[0]
    for line in txt.splitlines():
        s = line.strip().lstrip("#/' ").strip()
        if s and not s.startswith(("import", "from", "<!", "<")):
            return s[:120]
    return ""

# ---------- scanners ----------
def scan_tools():
    rows = []
    for p in sorted(glob.glob(os.path.join(ROOT, "tools", "*.py"))):
        rows.append("- `tools/%s` - %s" % (os.path.basename(p), first_doc(p)))
    return "\n".join(rows)

def scan_plugins():
    rows = []
    for p in sorted(glob.glob(os.path.join(ROOT, "plugins", "*.py"))):
        if os.path.basename(p).startswith("__"): continue
        txt = read(p)
        name = re.search(r'plugin_name"\s*:\s*"([^"]+)"', txt)
        ver = re.search(r'plugin_version"\s*:\s*"([^"]+)"', txt)
        intents = re.search(r'supported_intents"\s*:\s*\[([^\]]*)\]', txt)
        rows.append("- **%s** v%s (intents: %s) - `plugins/%s`" % (
            name.group(1) if name else os.path.basename(p)[:-3],
            ver.group(1) if ver else "?",
            (intents.group(1).replace('"', '').strip() if intents else "?"),
            os.path.basename(p)))
    return "\n".join(rows) or "- (none)"

def scan_skills():
    rows = []
    for d in sorted(glob.glob(os.path.join(ROOT, ".claude", "skills", "*"))):
        sk = os.path.join(d, "SKILL.md")
        if not os.path.isfile(sk): continue
        txt = read(sk)
        desc = re.search(r'description:\s*"?(.+)', txt)
        rows.append("- **%s** - %s" % (os.path.basename(d),
                    (desc.group(1).strip().strip('"')[:130] if desc else "")))
    ext = read(os.path.join(ROOT, ".claude", "skills", "EXTERNAL-SKILLS.md"))
    note = "\n\nExternal skill packs are documented in `.claude/skills/EXTERNAL-SKILLS.md`." if ext else ""
    return ("\n".join(rows) or "- (none)") + note

def scan_automation():
    rows = []
    for pat in ("*.bat", "*.vbs", os.path.join("tools", "*.ps1"), os.path.join("tools", "*.vbs")):
        for p in sorted(glob.glob(os.path.join(ROOT, pat))):
            rows.append("- `%s`" % os.path.relpath(p, ROOT).replace("\\", "/"))
    return "\n".join(sorted(set(rows))) or "- (none)"

def scan_commands():
    txt = read(os.path.join(ROOT, "tools", "zoe_router.py"))
    actions = re.findall(r'if a == "(\w+)"', txt) + re.findall(r'elif a == "(\w+)"', txt)
    intents = re.search(r'"action": "([^"]+)"', txt)
    return ("Action types (one router, used by voice + command bar + 3D console + control endpoint):\n\n"
            + "- " + (intents.group(1) if intents else ", ".join(sorted(set(actions))))
            + "\n\nNatural-language and direct commands both flow through `zoe_router.process()`. "
            "Native execution: Electron control endpoint `:7766` (`/action`, `/voice`, `/wake`). "
            "See COMMAND_SYSTEM_GUIDE.md for the full map.")

def scan_connectors():
    found = []
    for cfg in (".mcp.json", os.path.join(".claude", "settings.json"),
                os.path.join(".claude", "settings.local.json")):
        if os.path.isfile(os.path.join(ROOT, cfg)):
            found.append("- `%s`" % cfg)
    body = ("Native bridges (Zoe's own connectors):\n"
            "- Groq (llama-3.3-70b) - intent + chat\n- Deepgram (nova-2) - speech to text\n"
            "- ElevenLabs (Lily) - text to speech\n- psutil - live telemetry\n"
            "- Electron control endpoint :7766 - native OS actions\n\n"
            "Keys live in `.env` (gitignored). MCP servers/connectors are session/environment level "
            "(see the Claude config). Local config files found:\n" + ("\n".join(found) or "- (none in repo)"))
    return body

def git_changelog():
    log = sh(["git", "log", "-30", "--pretty=- %ad %s", "--date=short"])
    return log or "- (git log unavailable)"

def project_state():
    branch = sh(["git", "rev-parse", "--abbrev-ref", "HEAD"])
    head = sh(["git", "log", "-1", "--pretty=%h %s (%ad)", "--date=short"])
    pyc = len(glob.glob(os.path.join(ROOT, "tools", "*.py")))
    skills = len([d for d in glob.glob(os.path.join(ROOT, ".claude", "skills", "*")) if os.path.isdir(d)])
    plugins = len([p for p in glob.glob(os.path.join(ROOT, "plugins", "*.py")) if not os.path.basename(p).startswith("__")])
    return ("- branch: `%s`\n- HEAD: %s\n- python tools: %d\n- skills installed: %d\n- plugins: %d\n- generated: %s"
            % (branch or "?", head or "?", pyc, skills, plugins, NOW))

# ---------- doc bodies ----------
def architecture():
    return ("# Architecture\n\n"
        "ZOE / JARVIS is an Electron + Python desktop AI OS. ONE command pipeline; everything else feeds it.\n\n"
        "## Components\n"
        "| Layer | Files | Role |\n|---|---|---|\n"
        "| Command pipeline | `tools/zoe_router.py` | the single brain: classify -> explain -> execute -> record (process/route) |\n"
        "| Voice | `tools/zoe_assistant.py` | mic -> Deepgram -> router -> ElevenLabs; wake word, auto-calibrated mic |\n"
        "| Command bar / 3D console | `tools/zoe_cli.py`, server `/command` | typed text -> same pipeline |\n"
        "| Versioned kernel | `tools/zoe_versions.py`, `plugins/`, `tools/zoe_diagnostics.py` | locked schemas, plugin API, health |\n"
        "| Runtime memory | `tools/zoe_state.py` | `memory/zoe_state.json` (session, history, workspace, mode) |\n"
        "| Long-term memory | `tools/zoe_memory.py` | the Obsidian vault (`vault/`): write/read/sync/resume/graph |\n"
        "| Electron shell | `electron/main.js` + services | window, tray, shortcuts, control :7766, auto-start, mic perm |\n"
        "| Telemetry + API | `tools/zoe_server.py` :7717 | `/stats /3d /command /memory/* /session/resume /memory/graph` |\n"
        "| UI | `zoe-ui/index.html` (deck), `zoe-ui/os3d.html` (3D graph), `electron/palette.html` (command bar) |\n"
        "| Evolution / persistent memory | `tools/zoe_evolution.py`, `project-memory/` | auto-generated indexes (this system) |\n\n"
        "## Data flow (a command)\n"
        "```\nvoice/text/3D -> zoe_router.process() -> classify(Groq) -> execute -> POST :7766 (Electron) -> native action\n"
        "             -> record to zoe_state + vault command log -> spoken/displayed reply\n```\n\n"
        "Backwards compatibility is a hard rule: features are extended, never removed. See "
        "`COMMAND_SYSTEM_GUIDE.md` for the full command reference and `memory-bank/handoff.md` for history.\n")

def master():
    return ("# MASTER MEMORY  (read this first)\n\n"
        "The single entry point for any Zoe / Claude Code session. Generated %s.\n\n"
        "## Persistent project memory (project-memory/)\n"
        "- [[ARCHITECTURE]] - components + data flow\n"
        "- [[PROJECT_STATE]] - current branch/HEAD/counts\n"
        "- [[FEATURE_INDEX]] / [[COMMAND_REFERENCE]] - what Zoe can do\n"
        "- [[PLUGIN_INDEX]] / [[SKILL_INDEX]] / [[CONNECTOR_INDEX]] / [[AUTOMATION_INDEX]]\n"
        "- [[CHANGELOG]] - recent commits\n- [[SESSION_HISTORY]] - past Claude sessions\n"
        "- [[ROADMAP]] / [[CURRENT_TASK]] / [[KNOWN_ISSUES]]\n\n"
        "## The other memory layers (do not duplicate -- extend these)\n"
        "- `memory-bank/*.md` - curated identity/career/projects/handoff (hand-maintained)\n"
        "- `vault/` - the Obsidian long-term memory (notes, sessions, command log, graph)\n"
        "- `memory/zoe_state.json` - fast runtime state\n"
        "- `COMMAND_SYSTEM_GUIDE.md`, `JARVIS.md`, `README.md` - guides\n\n"
        "## Rule for every session\n"
        "1. Read this + `memory-bank/handoff.md` first. 2. Run `python tools/zoe_evolution.py` to refresh "
        "these indexes from reality. 3. Before finishing, run it with `--session \"<summary>\"`. "
        "Nothing is registered by hand; the evolution engine documents the project from the code itself.\n"
        % NOW)

def main():
    files = {
        "MASTER_MEMORY.md": master(),
        "ARCHITECTURE.md": architecture(),
        "PROJECT_STATE.md": "# Project State\n\n" + project_state(),
        "FEATURE_INDEX.md": "# Feature Index\n\nZoe's tools (auto-scanned):\n\n" + scan_tools(),
        "COMMAND_REFERENCE.md": "# Command Reference\n\n" + scan_commands(),
        "PLUGIN_INDEX.md": "# Plugin Index\n\n" + scan_plugins(),
        "SKILL_INDEX.md": "# Skill Index\n\n" + scan_skills(),
        "CONNECTOR_INDEX.md": "# Connector Index\n\n" + scan_connectors(),
        "AUTOMATION_INDEX.md": "# Automation Index\n\nScripts and launchers:\n\n" + scan_automation(),
        "CHANGELOG.md": "# Changelog (recent commits)\n\n" + git_changelog(),
        "ROADMAP.md": "# Roadmap\n\nForward work is tracked in `memory-bank/handoff.md` (backlog B/K items). "
                      "This file is the high-level view; edit freely.\n",
        "CURRENT_TASK.md": "# Current Task\n\nSee the latest entry in `memory-bank/handoff.md`. Update this "
                           "with the active focus at the start of a session.\n",
        "KNOWN_ISSUES.md": "# Known Issues\n\n- Installed app must be rebuilt (`npm run dist`) to ship UI/feature "
                           "changes.\n- 3D views load Three.js from a CDN (needs internet).\n- Mic threshold "
                           "(ZOE_MIC_THRESHOLD in .env) may need tuning per environment.\n",
    }
    ok = sum(1 for n, b in files.items() if write(n, b))

    # session history (append-only)
    if "--session" in sys.argv:
        i = sys.argv.index("--session")
        summary = " ".join(sys.argv[i + 1:]).strip() or "(no summary)"
        path = os.path.join(PM, "SESSION_HISTORY.md")
        if not os.path.exists(path):
            write("SESSION_HISTORY.md", "# Session History\n\nAppend-only log of Claude Code sessions.\n")
        try:
            with open(path, "a", encoding="utf-8") as f:
                f.write("\n## %s\n%s\n" % (NOW, summary))
        except Exception:
            pass
    elif not os.path.exists(os.path.join(PM, "SESSION_HISTORY.md")):
        write("SESSION_HISTORY.md", "# Session History\n\nAppend-only log of Claude Code sessions.\n")

    # mirror the key indexes into the Obsidian vault so they are searchable there too
    synced = 0
    try:
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
        import zoe_memory
        for n in ("MASTER_MEMORY", "ARCHITECTURE", "FEATURE_INDEX", "COMMAND_REFERENCE",
                  "PLUGIN_INDEX", "SKILL_INDEX"):
            p = os.path.join(PM, n + ".md")
            if os.path.exists(p):
                zoe_memory.write(n, read(p), folder="system", tags=["system", "auto"]); synced += 1
    except Exception:
        pass
    print("evolution: wrote %d/%d project-memory files; synced %d to the vault." % (ok, len(files) + 1, synced))

if __name__ == "__main__":
    main()
